spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/weather
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    driver: com.mysql.cj.jdbc.Driver
 